<a href="https://colab.research.google.com/github/2303A52187/GENERATIVE_AI_2025/blob/main/2303A52187_WEEK1_ASSIGNMENT_NO_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
from math import sqrt
from sklearn.linear_model import LinearRegression
# Actual values and predicted values
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])
# Calculate error metrics
mae = mean_absolute_error(y_actual, y_pred)  # Mean Absolute Error
mse = mean_squared_error(y_actual, y_pred)  # Mean Squared Error
rmse = sqrt(mse)  # Root Mean Squared Error
# Print error metrics
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Mean Squared Error (MSE): {mse}')
print(f'Root Mean Squared Error (RMSE): {rmse}')
# Simple Linear Regression
X = y_actual.reshape(-1, 1)  # Reshape data for scikit-learn (2D array for the independent variable)
y = y_pred  # Target (dependent variable)
# Create and fit the linear regression model
model = LinearRegression()
model.fit(X, y)
# Print the model's coefficients and intercept
print(f'Linear Regression Coefficients: {model.coef_}')
print(f'Linear Regression Intercept: {model.intercept_}')
# Predict using the linear regression model
y_pred_lr = model.predict(X)
# Print predicted values from the linear regression model
print(f'Predicted values using Linear Regression: {y_pred_lr}')

Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
Linear Regression Coefficients: [1.007]
Linear Regression Intercept: 0.17999999999999972
Predicted values using Linear Regression: [20.32 30.39 40.46 50.53 60.6 ]


In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2])
accuracy = accuracy_score(Y_actual, Y_pred)
precision = precision_score(Y_actual, Y_pred, average=None)
recall = recall_score(Y_actual, Y_pred, average=None)
f1 = f1_score(Y_actual, Y_pred, average=None)
conf_matrix = confusion_matrix(Y_actual, Y_pred)
print("Accuracy:", accuracy)
for i in range(len(precision)):
    print(f"Class {i}: Precision = {precision[i]}, Recall = {recall[i]}, F1-Score = {f1[i]}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nDetailed Classification Report:")
print(classification_report(Y_actual, Y_pred))

Accuracy: 0.7333333333333333
Class 0: Precision = 0.7777777777777778, Recall = 0.6363636363636364, F1-Score = 0.7
Class 1: Precision = 0.7142857142857143, Recall = 0.625, F1-Score = 0.6666666666666666
Class 2: Precision = 0.7142857142857143, Recall = 0.9090909090909091, F1-Score = 0.8

Confusion Matrix:
[[ 7  2  2]
 [ 1  5  2]
 [ 1  0 10]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74      0.73      0.73        30

